# ============================================================
# Docker Compose — SafeSpace Microservices (Supabase Version)
# ============================================================
services:

  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    container_name: safespace-auth-service
    restart: unless-stopped
    environment:
      # Mengambil dari .env root
      DATABASE_URL: ${AUTH_DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8001/health')"]
      interval: 20s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  item-service:
    build:
      context: ./services/item-service
      dockerfile: Dockerfile
    container_name: safespace-item-service
    restart: unless-stopped
    environment:
      # Mengambil dari .env root
      DATABASE_URL: ${ITEM_DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      AUTH_SERVICE_URL: http://auth-service:8001
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - "8002:8002"
    depends_on:
      auth-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8002/health')"]
      interval: 20s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  gateway:
    image: nginx:alpine
    container_name: safespace-gateway
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./services/gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      auth-service:
        condition: service_healthy
      item-service:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_AUTH_API_URL: http://localhost:8001
        VITE_ITEM_API_URL: http://localhost:8002
    container_name: safespace-frontend
    restart: unless-stopped
    depends_on:
      gateway:
        condition: service_started

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: safespace-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - auth-service
      - item-service

  grafana:
    image: grafana/grafana:latest
    container_name: safespace-grafana
    ports:
      - "3002:3000"  # Port default untuk membuka dashboard Grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Password default untuk login nanti
    depends_on:
      - prometheus
    volumes:
      - ./monitoring/grafana-data:/var/lib/grafana