server {
    listen 80;

    # Rute untuk Auth Service
    location /auth/ {
        proxy_pass http://auth-service:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Rute untuk Item Service
    location /items/ {
        proxy_pass http://item-service:8002/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}